"use client";

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { ArrowLeft, ArrowRight, BadgeCheck, BookOpen, Check, ChevronRight, CircleUserRound, Heart, Home, House, MapPin, Menu, PawPrint, Search, Send, ShieldCheck, Stethoscope, Upload, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import { toast, Toaster } from "sonner";

type View = "browse" | "home" | "guide" | "submit" | "account" | "admin";
type Cat = { id:string; name:string; image:string; age:string; ageGroup:"幼猫"|"成年猫"; sex:"男生"|"女生"; district:string; vaccine:"已接种"|"待接种"|"未知"; neutered:"已绝育"|"待绝育"|"未知"; status:"等待领养"|"沟通中"|"试养中"|"已到家"; traits:string[]; story:string; match:string[]; rescue:string; days?:number };

const cats: Cat[] = [
  { id:"naitang", name:"奶糖", image:"/cats/naitang.png", age:"8个月", ageGroup:"幼猫", sex:"女生", district:"香洲", vaccine:"已接种", neutered:"已绝育", status:"等待领养", traits:["亲人","活泼","新手友好"], story:"奶糖是在老旧小区的车底被发现的。她喜欢跟着人走，也会在你工作时安静趴在旁边。", rescue:"2026年7月救助，目前在志愿者家中寄养。", match:["完成封窗","家庭成员同意","接受定期回访"] },
  { id:"zhima", name:"芝麻", image:"/cats/zhima.png", age:"1岁", ageGroup:"成年猫", sex:"男生", district:"香洲", vaccine:"已接种", neutered:"已绝育", status:"沟通中", traits:["慢热","安静","可与猫相处"], story:"芝麻初见会有些谨慎，熟悉以后会主动靠近。他不吵闹，很适合生活节奏稳定的家庭。", rescue:"在小区投喂点完成绝育后进入寄养。", match:["愿意给适应时间","已有猫可科学隔离","完全室内饲养"] },
  { id:"xiaoyu", name:"小雨", image:"/cats/xiaoyu.png", age:"3个月", ageGroup:"幼猫", sex:"女生", district:"斗门", vaccine:"待接种", neutered:"待绝育", status:"等待领养", traits:["好奇","喜欢抱抱","新手友好"], story:"雨天里被店主捡到的小朋友，亲人、爱玩，对新环境适应得很快。", rescue:"已完成基础体检与首次驱虫。", match:["按时完成疫苗","适龄后绝育","家中无开放阳台"] },
  { id:"doudou", name:"豆豆", image:"/cats/zhima.png", age:"2岁", ageGroup:"成年猫", sex:"女生", district:"金湾", vaccine:"已接种", neutered:"已绝育", status:"试养中", traits:["稳重","不喜欢被抱","可与猫相处"], story:"豆豆很有边界感，也很会用自己的方式陪伴人。她正在一个安静家庭中试养。", rescue:"由社区志愿者持续照顾半年。", match:["尊重猫咪边界","接受试养回访","科学喂养"] },
  { id:"pipi", name:"皮皮", image:"/cats/naitang.png", age:"10个月", ageGroup:"幼猫", sex:"男生", district:"横琴", vaccine:"已接种", neutered:"已绝育", status:"等待领养", traits:["活泼","可与猫相处","需要陪伴"], story:"皮皮精力充沛、喜欢逗猫棒，适合愿意每天陪玩并做好环境丰富化的家庭。", rescue:"横琴工地救助，已完成社会化。", match:["每天稳定陪玩","不笼养","接受回访"] },
  { id:"mianmian", name:"绵绵", image:"/cats/xiaoyu.png", age:"6个月", ageGroup:"幼猫", sex:"女生", district:"香洲", vaccine:"已接种", neutered:"待绝育", status:"已到家", traits:["亲人","安静","儿童友好"], story:"绵绵已经遇见了她的新家。现在最喜欢的事，是在窗边晒太阳。", rescue:"等待了34天，于2026年9月12日正式到家。", match:["已完成封窗","按计划绝育","持续回访中"], days:34 },
];
const statusTone:Record<Cat["status"],string>={"等待领养":"status waiting","沟通中":"status talking","试养中":"status trial","已到家":"status home"};

export function YoujiaApp(){
  const [ready,setReady]=useState<boolean|null>(null),[view,setView]=useState<View>("browse"),[selected,setSelected]=useState<Cat|null>(null),[favorites,setFavorites]=useState<string[]>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("全部状态"),[age,setAge]=useState("全部年龄"),[sex,setSex]=useState("全部性别"),[district,setDistrict]=useState("全部区域"),[loginOpen,setLoginOpen]=useState(false),[loggedIn,setLoggedIn]=useState(false),[applicationOpen,setApplicationOpen]=useState(false),[applicationStep,setApplicationStep]=useState(1),[applicationSent,setApplicationSent]=useState(false),[mobileNav,setMobileNav]=useState(false);
  useEffect(()=>{setReady(localStorage.getItem("youjia-ready")==="yes");setFavorites(JSON.parse(localStorage.getItem("youjia-favorites")||"[]"));setLoggedIn(localStorage.getItem("youjia-demo-login")==="yes")},[]);
  const filtered=useMemo(()=>cats.filter(c=>(status==="全部状态"||c.status===status)&&(age==="全部年龄"||c.ageGroup===age)&&(sex==="全部性别"||c.sex===sex)&&(district==="全部区域"||c.district===district)&&(!query||`${c.name}${c.traits.join("")}`.includes(query))),[status,age,sex,district,query]);
  const go=(next:View)=>{setView(next);setMobileNav(false);scrollTo({top:0,behavior:"smooth"})};
  const toggleFavorite=(id:string)=>{const next=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(next);localStorage.setItem("youjia-favorites",JSON.stringify(next));toast(next.includes(id)?"已收藏，慢慢了解 TA":"已取消收藏")};
  const startApply=()=>{if(!loggedIn){setLoginOpen(true);return}setApplicationStep(1);setApplicationSent(false);setApplicationOpen(true)};
  if(ready===null)return <main className="min-h-screen bg-[#f7f4ee]"/>;
  if(!ready)return <Readiness onEnter={()=>{localStorage.setItem("youjia-ready","yes");setReady(true);scrollTo(0,0)}} onGuide={()=>{localStorage.setItem("youjia-ready","yes");setReady(true);setView("guide");scrollTo(0,0)}}/>;
  return <div className="min-h-screen bg-[#f7f4ee] text-[#24312b]"><Toaster position="top-center" richColors/><Header view={view} go={go} loggedIn={loggedIn} onLogin={()=>setLoginOpen(true)} mobileNav={mobileNav} setMobileNav={setMobileNav}/>
    {view==="browse"&&<Browse cats={filtered} favorites={favorites} onSelect={setSelected} toggleFavorite={toggleFavorite} query={query} setQuery={setQuery} filters={{status,age,sex,district}} setters={{setStatus,setAge,setSex,setDistrict}} reset={()=>{setQuery("");setStatus("全部状态");setAge("全部年龄");setSex("全部性别");setDistrict("全部区域")}}/>}
    {view==="home"&&<HomeWall go={go}/>} {view==="guide"&&<Guide/>} {view==="submit"&&<Submit loggedIn={loggedIn} onLogin={()=>setLoginOpen(true)}/>} {view==="account"&&<Account loggedIn={loggedIn} onLogin={()=>setLoginOpen(true)} favorites={favorites} onSelect={id=>setSelected(cats.find(c=>c.id===id)||null)}/>} {view==="admin"&&<Admin/>}<Footer go={go}/>
    <Sheet open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><SheetContent className="detail-sheet" side="right">{selected&&<CatDetail cat={selected} favorite={favorites.includes(selected.id)} toggleFavorite={()=>toggleFavorite(selected.id)} onApply={startApply}/>}</SheetContent></Sheet>
    <LoginDialog open={loginOpen} onOpenChange={setLoginOpen} onSuccess={()=>{setLoggedIn(true);localStorage.setItem("youjia-demo-login","yes");setLoginOpen(false);toast.success("登录成功")}}/>
    <ApplicationDialog cat={selected} open={applicationOpen} onOpenChange={setApplicationOpen} step={applicationStep} setStep={setApplicationStep} sent={applicationSent} onSubmit={()=>{setApplicationSent(true);toast.success("申请已提交")}}/>
  </div>
}

function Header({view,go,loggedIn,onLogin,mobileNav,setMobileNav}:{view:View;go:(v:View)=>void;loggedIn:boolean;onLogin:()=>void;mobileNav:boolean;setMobileNav:(v:boolean)=>void}){const items:[View,string][]=[["browse","找猫"],["home","已到家"],["guide","养猫指南"],["submit","我要送养"]];return <header className="site-header"><div className="header-inner"><button className="brand" onClick={()=>go("browse")} aria-label="有家计划首页"><span className="brand-mark"><PawPrint/></span><span><b>有家计划</b><small>珠海流浪猫领养</small></span></button><nav className={mobileNav?"nav open":"nav"}>{items.map(([k,l])=><button key={k} className={view===k?"active":""} onClick={()=>go(k)}>{l}</button>)}<button onClick={()=>go("admin")}>机构工作台</button></nav><div className="header-actions"><button className="account-button" onClick={()=>loggedIn?go("account"):onLogin()}><CircleUserRound/>{loggedIn?"我的":"登录"}</button><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)}>{mobileNav?<X/>:<Menu/>}</button></div></div></header>}

function Readiness({onEnter,onGuide}:{onEnter:()=>void;onGuide:()=>void}){return <main className="readiness"><div className="readiness-photo"><Image src="/cats/naitang.png" alt="等待领养的橘白猫奶糖" fill priority sizes="(max-width:800px) 100vw,48vw"/></div><section className="readiness-copy"><div className="eyebrow"><PawPrint/>领养前，请认真读完</div><h1>带 TA 回家，<br/><em>是一生的约定。</em></h1><p className="lead">TA 可能只是你人生的一部分，但你会成为 TA 很长时间里的家。</p><div className="commitments">{[[Home,"安全的家","封窗、室内饲养，并为搬家和生活变化做好安排"],[Stethoscope,"持续的照顾","承担疫苗、绝育、日常与生病时的医疗费用"],[Heart,"足够的耐心","接受磨合期，不因抓挠、胆小或暂时不亲人而放弃"]].map(([Icon,title,text]:any)=><div key={title}><span><Icon/></span><p><b>{title}</b><small>{text}</small></p></div>)}</div><div className="readiness-question">你准备好让家里多一个成员了吗？</div><button className="primary wide" onClick={onEnter}>我准备好了，去看看它们<ArrowRight/></button><button className="text-button" onClick={onGuide}>我想先了解如何照顾猫咪</button></section></main>}

function Browse({cats,favorites,onSelect,toggleFavorite,query,setQuery,filters,setters,reset}:{cats:Cat[];favorites:string[];onSelect:(c:Cat)=>void;toggleFavorite:(id:string)=>void;query:string;setQuery:(v:string)=>void;filters:any;setters:any;reset:()=>void}){const opts=[["status",["全部状态","等待领养","沟通中","试养中","已到家"],setters.setStatus],["age",["全部年龄","幼猫","成年猫"],setters.setAge],["sex",["全部性别","女生","男生"],setters.setSex],["district",["全部区域","香洲","斗门","金湾","横琴"],setters.setDistrict]] as const;return <main><section className="browse-hero"><div><div className="eyebrow">珠海 · 领养代替购买</div><h1>在这里，遇见<br/>正在等家的 TA</h1><p>每一条信息都经过合作机构审核。先了解，再决定，给彼此一个认真开始的机会。</p></div><div className="hero-note"><span>本周新成员</span><b>3</b><small>只猫咪通过审核，开始等待新家</small></div></section><section className="browse-shell"><div className="filter-bar"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名字或性格"/></label><div className="filters">{opts.map(([k,vs,setter])=><select key={k} value={filters[k]} onChange={e=>setter(e.target.value)}>{vs.map(v=><option key={v}>{v}</option>)}</select>)}</div></div><div className="results-head"><p><b>{cats.length}</b> 位小朋友</p><span>优先展示正在等待领养的猫咪</span></div>{cats.length?<div className="cat-grid">{cats.map(c=><CatCard key={c.id} cat={c} favorite={favorites.includes(c.id)} onSelect={()=>onSelect(c)} onFavorite={()=>toggleFavorite(c.id)}/>)}</div>:<div className="empty-state"><PawPrint/><h2>暂时没有符合条件的猫咪</h2><p>换一组筛选条件，也许会遇见新的缘分。</p><button className="secondary" onClick={reset}>清除筛选</button></div>}</section></main>}

function CatCard({cat,favorite,onSelect,onFavorite}:{cat:Cat;favorite:boolean;onSelect:()=>void;onFavorite:()=>void}){return <article className={`cat-card ${cat.status==="已到家"?"graduated":""}`}><div className="cat-photo" onClick={onSelect}><Image src={cat.image} alt={`${cat.name}的领养照片`} fill sizes="(max-width:700px) 50vw,28vw"/><span className={statusTone[cat.status]}>{cat.status}</span></div><button className={favorite?"heart liked":"heart"} onClick={onFavorite}><Heart fill={favorite?"currentColor":"none"}/></button><button className="cat-info" onClick={onSelect}><div><h2>{cat.name}</h2><span>{cat.age} · {cat.sex}</span></div><p><MapPin/>{cat.district}<span>·</span>{cat.vaccine}</p><div className="trait-row">{cat.traits.slice(0,2).map(t=><span key={t}>{t}</span>)}</div></button></article>}

function CatDetail({cat,favorite,toggleFavorite,onApply}:{cat:Cat;favorite:boolean;toggleFavorite:()=>void;onApply:()=>void}){return <div className="detail"><div className="detail-photo"><Image src={cat.image} alt={`${cat.name}的照片`} fill sizes="(max-width:700px) 100vw,46vw"/><span className={statusTone[cat.status]}>{cat.status}</span></div><div className="detail-body"><SheetHeader className="detail-title"><div><div className="eyebrow"><MapPin/>珠海市{cat.district}区</div><SheetTitle>{cat.name}</SheetTitle><SheetDescription>{cat.age} · {cat.sex} · {cat.neutered}</SheetDescription></div><button className={favorite?"detail-heart liked":"detail-heart"} onClick={toggleFavorite}><Heart fill={favorite?"currentColor":"none"}/></button></SheetHeader><section><h3>关于我</h3><div className="trait-row large">{cat.traits.map(t=><span key={t}>{t}</span>)}</div><p>{cat.story}</p><p className="muted">{cat.rescue}</p></section><section><h3>健康档案</h3><div className="health-grid">{[["疫苗",cat.vaccine],["绝育",cat.neutered],["驱虫","已完成"],["传染病检查","阴性"]].map(([k,v])=><div key={k}><span>{k}</span><b><Check/>{v}</b></div>)}</div></section><section><h3>TA 希望找到这样的家</h3><ul className="match-list">{cat.match.map(x=><li key={x}><Check/>{x}</li>)}</ul></section>{cat.status==="已到家"?<div className="home-banner"><House/><div><b>{cat.name}已经找到家啦</b><span>等待了 {cat.days} 天，感谢每一位关注过 TA 的人。</span></div></div>:<div className="sticky-action"><button className="primary wide" onClick={onApply}>申请领养 {cat.name}<ArrowRight/></button><small>提交完整申请后可查看送养人联系方式</small></div>}</div></div>}

function LoginDialog({open,onOpenChange,onSuccess}:{open:boolean;onOpenChange:(v:boolean)=>void;onSuccess:()=>void}){const[phone,setPhone]=useState(""),[code,setCode]=useState(""),[sent,setSent]=useState(false);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="login-dialog"><DialogHeader><span className="dialog-icon"><ShieldCheck/></span><DialogTitle>登录后继续</DialogTitle><DialogDescription>用于保存申请进度和保护送养人的联系方式。</DialogDescription></DialogHeader><label>手机号<Input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,11))} placeholder="请输入 11 位手机号"/></label><label>验证码<div className="code-row"><Input value={code} onChange={e=>setCode(e.target.value.slice(0,4))} placeholder="4 位验证码"/><button className="secondary" onClick={()=>{setSent(true);toast("体验验证码：0520")}}>{sent?"重新发送":"获取验证码"}</button></div></label><p className="demo-hint">体验版本验证码为 <b>0520</b>。正式运营时接入短信服务。</p><button className="primary wide" disabled={phone.length!==11||code!=="0520"} onClick={onSuccess}>安全登录</button><small className="terms">登录即表示同意《用户协议》和《隐私政策》</small></DialogContent></Dialog>}

function ApplicationDialog({cat,open,onOpenChange,step,setStep,sent,onSubmit}:{cat:Cat|null;open:boolean;onOpenChange:(v:boolean)=>void;step:number;setStep:(v:number)=>void;sent:boolean;onSubmit:()=>void}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="application-dialog">{sent?<div className="success-state"><span><Check/></span><h2>申请已提交</h2><p>这不代表申请已经通过。请先与送养人充分沟通，再安排见猫和交接。</p><div className="contact-card"><small>送养人联系方式</small><b>微信：ZH-rescue-07</b><span>查看行为已记录，请勿转发或骚扰。</span></div><button className="primary wide" onClick={()=>onOpenChange(false)}>知道了</button></div>:<><DialogHeader><DialogTitle>申请领养 {cat?.name}</DialogTitle><DialogDescription>第 {step} 步，共 3 步 · 表单会自动保存草稿</DialogDescription></DialogHeader><Progress value={step/3*100}/>{step===1&&<div className="form-step"><h3>先认识一下你</h3><div className="two-cols"><label>姓名<Input placeholder="怎么称呼你"/></label><label>年龄范围<select><option>请选择</option><option>18–24 岁</option><option>25–34 岁</option><option>35 岁以上</option></select></label></div><label>微信号<Input placeholder="方便送养人与你联系"/></label><label>所在区域<select><option>香洲区</option><option>斗门区</option><option>金湾区</option><option>横琴粤澳深度合作区</option></select></label></div>}{step===2&&<div className="form-step"><h3>你的居住环境</h3><label>目前的居住方式<select><option>独居</option><option>与家人居住</option><option>与伴侣居住</option><option>合租</option></select></label><label>窗户和阳台<select><option>已经完成封窗</option><option>愿意在接猫前完成</option><option>暂时无法封窗</option></select></label><CheckLine text="家庭成员或室友都同意养猫"/><CheckLine text="家中没有对猫严重过敏的成员"/><CheckLine text="租房已获得房东允许（自有住房可忽略）"/></div>}{step===3&&<div className="form-step"><h3>关于长期照顾</h3><label>猫咪每天大约独处多久？<select><option>少于 4 小时</option><option>4–8 小时</option><option>8–12 小时</option></select></label><label>如果未来搬家或工作变化，你会怎样安排 TA？<Textarea placeholder="请尽量具体地说说你的计划"/></label><label>如果 TA 生病、抓家具或暂时不亲人，你会怎么处理？<Textarea placeholder="你的真实想法比标准答案更重要"/></label><CheckLine text="我能够长期承担日常与必要医疗费用"/></div>}<div className="dialog-actions">{step>1&&<button className="secondary" onClick={()=>setStep(step-1)}><ArrowLeft/>上一步</button>}<button className="primary" onClick={()=>step<3?setStep(step+1):onSubmit()}>{step<3?<>下一步<ArrowRight/></>:<>确认提交<Send/></>}</button></div></>}</DialogContent></Dialog>}
function CheckLine({text}:{text:string}){return <label className="check-line"><Checkbox/><span>{text}</span></label>}

function HomeWall({go}:{go:(v:View)=>void}){const homeCats=cats.filter(c=>c.status==="已到家");return <main className="content-page"><section className="page-title"><div className="eyebrow"><House/>幸福毕业墙</div><h1>它们已经回家了</h1><p>每一个“已到家”，都来自一次认真了解和一段彼此适应的过程。</p></section><div className="stats"><div><b>{cats.length}</b><span>已发布</span></div><div><b>{cats.filter(c=>c.status==="等待领养").length}</b><span>等待中</span></div><div><b>{cats.filter(c=>c.status==="试养中").length}</b><span>试养中</span></div><div><b>{homeCats.length}</b><span>已到家</span></div></div><div className="home-grid">{homeCats.map(c=><article key={c.id}><Image src={c.image} alt={c.name} width={640} height={640}/><div><span>等待 {c.days} 天</span><h2>{c.name}</h2><p>2026年9月12日到家</p></div></article>)}</div><div className="cta-strip"><div><h2>还有小朋友正在等你</h2><p>先看看它们的故事，再决定是否准备好了。</p></div><button className="primary" onClick={()=>go("browse")}>去猫咪广场<ArrowRight/></button></div></main>}

function Guide(){const sections=[["01","接猫之前","完成封窗，准备航空箱、猫砂盆、食水碗和安静的适应空间。"],["02","到家第一周","给 TA 躲藏和观察的时间，不强行抱、不急着洗澡，也不要立即与原住民见面。"],["03","健康管理","按兽医建议完成驱虫、疫苗和绝育；精神、食欲或排泄异常时及时就医。"],["04","科学喂养","提供适龄主食和清洁饮水，避免人类食物、牛奶以及对猫有毒的植物。"],["05","多猫隔离","新猫先单独隔离，交换气味、逐步见面，并准备足够的猫砂盆和资源点。"],["06","紧急情况","持续呕吐、呼吸困难、无法排尿、误食异物等情况需要尽快联系医院。"]];return <main className="content-page guide-page"><section className="page-title"><div className="eyebrow"><BookOpen/>新手养猫指南</div><h1>把喜欢，变成可靠的照顾</h1><p>这份指南帮助你做好基础准备，不能替代专业兽医的诊断。</p><small>由有家计划合作机构维护 · 更新于 2026年9月</small></section><div className="guide-grid">{sections.map(([n,t,p])=><article key={n}><span>{n}</span><div><h2>{t}</h2><p>{p}</p><button>查看详细清单<ChevronRight/></button></div></article>)}</div><aside className="guide-callout"><ShieldCheck/><div><h2>封窗不是选项，是安全底线</h2><p>普通纱窗无法承受猫咪扑撞。阳台、推拉窗和厨房窗都应使用牢固网格，并检查缝隙。</p></div></aside></main>}

function Submit({loggedIn,onLogin}:{loggedIn:boolean;onLogin:()=>void}){const[step,setStep]=useState(1),[done,setDone]=useState(false);if(!loggedIn)return <main className="center-page"><span className="big-icon"><Upload/></span><h1>我救助了一只猫</h1><p>个人可以提交送养资料，合作机构审核通过后才会公开展示。</p><button className="primary" onClick={onLogin}>登录后开始投稿<ArrowRight/></button></main>;if(done)return <main className="center-page"><span className="big-icon success"><Check/></span><h1>投稿已进入审核</h1><p>机构会核对健康信息、照片和领养条件，通常在 1–2 个工作日内反馈。</p><span className="review-id">投稿编号 YJ-0924-08</span><button className="secondary" onClick={()=>{setDone(false);setStep(1)}}>再提交一只猫</button></main>;return <main className="content-page submit-page"><section className="page-title compact"><div className="eyebrow"><Upload/>个人救助投稿</div><h1>为 TA 寻找一个可靠的家</h1><p>第 {step} 步，共 3 步 · 未提交前仅自己可见</p><Progress value={step/3*100}/></section><section className="submit-card">{step===1&&<div className="form-step"><h2>猫咪基本资料</h2><div className="two-cols"><label>名字<Input placeholder="暂时没有可填昵称"/></label><label>所在区域<select><option>香洲区</option><option>斗门区</option><option>金湾区</option><option>横琴</option></select></label><label>性别<select><option>未知</option><option>女生</option><option>男生</option></select></label><label>年龄<Input placeholder="如：约8个月"/></label></div><label>救助经历<Textarea placeholder="在哪里、什么时候、怎样遇见 TA？"/></label></div>}{step===2&&<div className="form-step"><h2>健康与性格</h2><div className="two-cols"><label>疫苗<select><option>未知</option><option>已完成</option><option>未完成</option></select></label><label>绝育<select><option>未知</option><option>已完成</option><option>未完成</option></select></label><label>驱虫<select><option>未知</option><option>已完成</option><option>未完成</option></select></label><label>传染病检查<select><option>未知</option><option>阴性</option><option>阳性或需说明</option></select></label></div><label>性格标签<Input placeholder="例如：亲人、慢热、可与猫相处"/></label><label>还有什么想告诉未来主人？<Textarea placeholder="生活习惯、喜欢和害怕的事……"/></label></div>}{step===3&&<div className="form-step"><h2>照片、交接与要求</h2><div className="upload-box"><Upload/><b>上传封面与生活照</b><span>封面 1 张，生活照最多 8 张 · JPG/PNG · 单张不超过 10MB</span><button className="secondary" onClick={()=>toast("体验版已保留上传入口")}>选择照片</button></div><label>交接方式<select><option>双方协商</option><option>领养人自提</option><option>送养人可送</option></select></label><label>希望领养家庭具备哪些条件？<Textarea placeholder="例如：封窗、家庭成员同意、接受回访"/></label></div>}<div className="dialog-actions">{step>1&&<button className="secondary" onClick={()=>setStep(step-1)}><ArrowLeft/>上一步</button>}<button className="primary" onClick={()=>step<3?setStep(step+1):setDone(true)}>{step<3?<>下一步<ArrowRight/></>:<>提交机构审核<Send/></>}</button></div></section></main>}

function Account({loggedIn,onLogin,favorites,onSelect}:{loggedIn:boolean;onLogin:()=>void;favorites:string[];onSelect:(id:string)=>void}){if(!loggedIn)return <main className="center-page"><span className="big-icon"><CircleUserRound/></span><h1>登录查看你的记录</h1><p>申请、投稿、收藏和回访任务都会保存在这里。</p><button className="primary" onClick={onLogin}>手机号登录</button></main>;const favCats=cats.filter(c=>favorites.includes(c.id));return <main className="content-page account-page"><section className="profile"><span>林</span><div><h1>林小满</h1><p>珠海 · 普通用户</p></div><button className="secondary">编辑资料</button></section><div className="account-stats"><div><b>1</b><span>领养申请</span></div><div><b>0</b><span>送养投稿</span></div><div><b>{favorites.length}</b><span>收藏猫咪</span></div><div><b>0</b><span>待办回访</span></div></div><section className="panel"><div className="panel-title"><div><h2>我的领养申请</h2><p>最近状态</p></div><button>查看全部</button></div><div className="application-row"><Image src="/cats/zhima.png" alt="芝麻" width={64} height={64}/><div><b>芝麻</b><span>申请编号 YJ-A-0182</span></div><span className="status talking">沟通中</span><small>更新于今天 10:24</small></div></section><section className="panel"><div className="panel-title"><div><h2>收藏的猫咪</h2><p>{favCats.length?"继续了解，再认真决定":"遇见喜欢的猫咪，可以先收藏"}</p></div></div>{favCats.length?<div className="mini-cats">{favCats.map(c=><button key={c.id} onClick={()=>onSelect(c.id)}><Image src={c.image} alt={c.name} width={72} height={72}/><span><b>{c.name}</b><small>{c.status}</small></span></button>)}</div>:<div className="mini-empty"><Heart/>还没有收藏</div>}</section></main>}

function Admin(){const[reviewed,setReviewed]=useState(false);return <main className="content-page admin-page"><section className="page-title compact"><div className="eyebrow"><BadgeCheck/>合作机构工作台</div><h1>今天有 4 件事需要处理</h1><p>审核投稿、跟进回访，并维护公开信息的准确性。</p></section><div className="admin-stats"><div><span>待审核投稿</span><b>{reviewed?2:3}</b><small>其中 1 条等待超过 24 小时</small></div><div><span>进行中申请</span><b>8</b><small>3 只猫处于沟通中</small></div><div><span>本周回访</span><b>2</b><small>7 天回访待完成</small></div></div><section className="panel"><div className="panel-title"><div><h2>投稿审核</h2><p>个人投稿需核验后公开</p></div><button>查看全部</button></div>{!reviewed?<div className="review-row"><Image src="/cats/xiaoyu.png" alt="待审核猫咪" width={76} height={76}/><div><b>暂名“小雪”</b><span>香洲 · 约4个月 · 投稿人陈女士</span><small>提交于今天 09:42</small></div><div className="review-actions"><button className="secondary" onClick={()=>toast("已标记需要补充疫苗凭证")}>要求修改</button><button className="primary" onClick={()=>{setReviewed(true);toast.success("审核通过，猫咪已公开")}}>通过并发布</button></div></div>:<div className="inline-success"><Check/>该投稿已通过审核并公开展示。</div>}</section><section className="panel"><div className="panel-title"><div><h2>待完成回访</h2><p>领养后 7 天与 30 天</p></div></div><div className="follow-row"><span className="calendar">7<span>天</span></span><div><b>绵绵 · 适应情况回访</b><span>领养人已上传 2 张近况照片</span></div><button className="secondary" onClick={()=>toast("回访记录已打开")}>填写记录</button></div></section><section className="panel audit"><div className="panel-title"><div><h2>最近操作记录</h2><p>机构审核与状态变更</p></div></div>{["管理员小周将「豆豆」更新为试养中","审核员阿宁退回投稿 YJ-0923-06","管理员小周完成「绵绵」7 天回访"].map((x,i)=><div key={x}><span/><p>{x}<small>{i===0?"今天 11:06":i===1?"昨天 18:20":"9月20日 14:12"}</small></p></div>)}</section></main>}
function Footer({go}:{go:(v:View)=>void}){return <footer><div className="footer-brand"><PawPrint/><div><b>有家计划</b><span>让每一份领养信息更清楚，让每一次决定更认真。</span></div></div><div><button onClick={()=>go("browse")}>找猫</button><button onClick={()=>go("guide")}>养猫指南</button><button onClick={()=>go("submit")}>我要送养</button><button onClick={()=>{localStorage.removeItem("youjia-ready");location.reload()}}>领养须知</button></div><small>© 2026 有家计划 · 珠海流浪猫领养</small></footer>}
